'use strict';

/**
 * Banco de palabras por categoría.
 *
 * Formato: "Palabra|pista fácil|pista media|pista difícil"
 *
 * Los tres niveles van de más a menos información. Ninguno nombra la palabra:
 *   Karate | "Artes marciales con cinturón y kata" | "Cinturón y kata" | "Cinturón"
 */

const RAW = [
  {
    id: 'peliculas',
    name: 'Películas',
    emoji: '🎬',
    words: [
      'Titanic|Un barco enorme choca con un iceberg|Barco e iceberg|Iceberg',
      'El Padrino|Una familia de la mafia italiana|Mafia italiana|Mafia',
      'Jurassic Park|Un parque lleno de dinosaurios|Parque con dinosaurios|Dinosaurios',
      'Matrix|Descubre que el mundo es una simulación|El mundo es simulado|Simulación',
      'Rápidos y Furiosos|Autos tuneados y carreras ilegales|Carreras ilegales|Carreras',
      'Shrek|Un ogro verde que vive en un pantano|Ogro en un pantano|Ogro',
      'Toy Story|Los juguetes cobran vida sin el niño|Juguetes que viven|Juguetes',
      'Avatar|Alienígenas azules altos en otro planeta|Alienígenas azules|Azules',
      'Harry Potter|Un niño mago con lentes y cicatriz|Niño mago con cicatriz|Magia',
      'El Señor de los Anillos|Hay que destruir un anillo en un volcán|Destruir un anillo|Anillo',
      'Star Wars|Espadas láser y una galaxia lejana|Espadas láser|Galaxia',
      'Rey León|Un cachorro que debe heredar la selva|Heredar la selva|Cachorro',
      'Frozen|Una reina que congela todo lo que toca|Reina que congela|Hielo',
      'Coco|Un niño viaja al mundo de los muertos|Mundo de los muertos|Muertos',
      'Batman|Millonario disfrazado de murciélago|Disfrazado de murciélago|Murciélago',
      'Spider-Man|Lo picó una araña y trepa paredes|Lo picó una araña|Telaraña',
      'Joker|El payaso que se ríe y da miedo|Payaso que da miedo|Risa',
      'Parasite|Una familia pobre se infiltra en una rica|Pobres se infiltran|Sótano',
      'El Resplandor|Un hotel vacío enloquece al papá|Hotel que enloquece|Hotel',
      'Tiburón|Un escualo gigante ataca bañistas|Escualo ataca bañistas|Aleta',
      'Volver al Futuro|Viaja al pasado en un auto|Auto que viaja en el tiempo|DeLorean',
      'Forrest Gump|Corre por todo el país sin parar|Corre sin parar|Correr',
      'Gladiador|Un romano pelea en el Coliseo|Pelea en el Coliseo|Coliseo',
      'Interstellar|Buscan otro planeta para la humanidad|Buscar otro planeta|Agujero',
      'Piratas del Caribe|Tesoros, barcos y un capitán borracho con rastas|Capitán con rastas|Tesoro',
      'Los Vengadores|Un equipo enorme de superhéroes|Equipo de superhéroes|Equipo',
      'Rocky|Un boxeador entrena subiendo escaleras|Boxeador que entrena|Boxeo',
      'E.T.|Un extraterrestre quiere volver a su casa|Extraterrestre quiere volver|Bicicleta',
      'La La Land|Bailan y cantan en Los Ángeles|Bailan en Los Ángeles|Musical',
      'Intensamente|Las emociones viven dentro de una niña|Emociones dentro de una niña|Emociones'
    ]
  },
  {
    id: 'animales',
    name: 'Animales',
    emoji: '🐾',
    words: [
      'Elefante|Gris, gigante, con trompa y colmillos|Trompa y colmillos|Trompa',
      'Jirafa|El cuello más largo de todos|Cuello larguísimo|Cuello',
      'Pingüino|Ave que no vuela y camina en el hielo|Ave que no vuela|Hielo',
      'Tiburón|Aleta que asoma en el mar|Aleta en el mar|Aleta',
      'Águila|Ave de rapiña que ve desde muy alto|Rapaz que ve lejos|Rapaz',
      'Cocodrilo|Reptil de río con mandíbula enorme|Reptil de río|Mandíbula',
      'Serpiente|Se arrastra y algunas tienen veneno|Se arrastra, veneno|Veneno',
      'Perro|Ladra y mueve la cola|Ladra y mueve la cola|Ladra',
      'Gato|Maúlla y siempre cae de pie|Maúlla, cae de pie|Maúlla',
      'Caballo|Se monta y galopa|Se monta y galopa|Galope',
      'León|Melena y ruge en la sabana|Melena y ruge|Melena',
      'Tigre|Naranjo con rayas negras|Naranjo con rayas|Rayas',
      'Oso|Grande, peludo e hiberna|Peludo, hiberna|Hibernar',
      'Mono|Se cuelga de los árboles y come plátanos|Se cuelga, come plátanos|Plátano',
      'Delfín|Salta en el mar y es muy listo|Salta en el mar|Salta',
      'Ballena|El animal más grande del océano|El más grande del mar|Enorme',
      'Murciélago|Cuelga de cabeza y vuela de noche|Cuelga de cabeza|Colgado',
      'Búho|Ojos enormes y gira la cabeza|Ojos enormes, de noche|Nocturno',
      'Abeja|Hace miel y pica|Hace miel y pica|Miel',
      'Hormiga|Diminuta y carga más que su peso|Diminuta y fuerte|Diminuta',
      'Araña|Ocho patas y teje telas|Ocho patas que tejen|Tejer',
      'Camello|Joroba y cruza el desierto|Joroba en el desierto|Joroba',
      'Canguro|Salta y lleva la cría en la bolsa|Salta con bolsa|Bolsa',
      'Koala|Se abraza a los árboles y duerme todo el día|Duerme en los árboles|Dormilón',
      'Zorro|Naranjo, astuto y de cola peluda|Astuto y naranjo|Astuto',
      'Lobo|Aúlla a la luna y anda en manada|Aúlla en manada|Aullido',
      'Rana|Verde, salta y croa|Verde, salta y croa|Croa',
      'Tortuga|Camina lentísimo con su caparazón|Lentísima, con caparazón|Caparazón',
      'Pulpo|Ocho tentáculos y suelta tinta|Tentáculos y tinta|Tentáculos',
      'Flamenco|Rosado y se para en una pata|Rosado, una pata|Rosado'
    ]
  },
  {
    id: 'anime',
    name: 'Anime',
    emoji: '🍥',
    words: [
      'Naruto|Ninja rubio que quiere ser Hokage|Ninja que será Hokage|Ninja',
      'Dragon Ball|Buscan siete esferas y se ponen rubios|Siete esferas|Esferas',
      'One Piece|Piratas buscando el tesoro más grande|Piratas buscando tesoro|Piratas',
      'Attack on Titan|Gigantes que comen gente tras los muros|Gigantes tras los muros|Muros',
      'Death Note|Un cuaderno que mata a quien escribas|Cuaderno que mata|Cuaderno',
      'Demon Slayer|Cazan criaturas nocturnas con espadas japonesas|Espadas contra criaturas|Espada',
      'My Hero Academia|Escuela donde todos tienen superpoderes|Escuela de poderes|Escuela',
      'Pokémon|Atrapa criaturas en bolitas rojas|Criaturas en bolitas|Bolita',
      'Sailor Moon|Chicas que se transforman con la luna|Chicas y la luna|Luna',
      'Evangelion|Adolescentes pilotean robots gigantes|Robots gigantes|Robots',
      'Fullmetal Alchemist|Dos hermanos alquimistas, uno es armadura|Hermanos alquimistas|Alquimia',
      'Jujutsu Kaisen|Estudiantes que pelean contra maldiciones|Pelean maldiciones|Maldición',
      'Bleach|Segador de almas con espada gigante|Segador con espada|Segador',
      'Tokyo Ghoul|Se convierte en algo que come humanos|Come humanos|Devora',
      'Hunter x Hunter|Un niño busca a su papá cazador|Busca a su papá|Examen',
      'Cowboy Bebop|Cazarrecompensas en una nave espacial|Cazarrecompensas espaciales|Nave',
      'Chainsaw Man|Un chico con motosierras en la cabeza|Motosierras en la cabeza|Motosierra',
      'Spy x Family|Un espía finge tener familia|Espía finge familia|Espía',
      'Haikyuu|Vóleibol de secundaria y un chico bajito|Vóleibol de secundaria|Vóleibol',
      'Slam Dunk|Básquetbol japonés y un pelirrojo|Básquetbol y pelirrojo|Básquetbol',
      'Inuyasha|Chica cae a un pozo y viaja al Japón feudal|Pozo al Japón feudal|Pozo',
      'Digimon|Niños con monstruos digitales|Monstruos digitales|Digital',
      'Doraemon|Gato robot azul con bolsillo mágico|Gato robot azul|Bolsillo',
      'Shingeki no Kyojin|Titanes que rompen las murallas|Titanes rompen murallas|Titanes',
      'Your Name|Dos jóvenes intercambian cuerpos|Intercambian cuerpos|Cuerpos',
      'El viaje de Chihiro|Niña atrapada en unos baños de espíritus|Baños de espíritus|Espíritus',
      'Mi vecino Totoro|Criatura gris gigante y un gato-bus|Criatura gris y gato-bus|Bosque',
      'Steins;Gate|Un microondas manda mensajes al pasado|Mensajes al pasado|Microondas',
      'Code Geass|Príncipe exiliado con poder de dar órdenes|Poder de dar órdenes|Órdenes',
      'Berserk|Guerrero con una espada descomunal|Espada descomunal|Espadón'
    ]
  },
  {
    id: 'comida',
    name: 'Comida',
    emoji: '🍕',
    words: [
      'Pizza|Redonda, con queso y se corta en triángulos|Redonda con queso|Triángulo',
      'Hamburguesa|Carne y verduras entre dos panes|Carne entre panes|Pan',
      'Sushi|Arroz y pescado crudo enrollado en alga|Arroz y pescado crudo|Alga',
      'Tacos|Tortilla doblada con carne y limón|Tortilla con carne|Tortilla',
      'Empanada|Masa horneada rellena de carne|Masa rellena|Relleno',
      'Asado|Carne a la parrilla con amigos|Carne a la parrilla|Parrilla',
      'Completo|Vienesa con palta, tomate y mayonesa|Vienesa con palta|Vienesa',
      'Pastel|Dulce de cumpleaños con velas|Dulce con velas|Velas',
      'Helado|Frío, dulce y en cono|Frío y en cono|Cono',
      'Chocolate|Barra dulce de cacao|Barra de cacao|Cacao',
      'Ensalada|Lechuga, tomate y poco más|Lechuga y tomate|Lechuga',
      'Sopa|Caldo caliente que se toma con cuchara|Caldo con cuchara|Caldo',
      'Arroz|Granos blancos que acompañan todo|Granos que acompañan|Granos',
      'Papas Fritas|Bastoncitos crujientes con ketchup|Bastoncitos crujientes|Crujiente',
      'Pan|Se hornea, se corta en rebanadas|Se hornea y se rebana|Miga',
      'Queso|Amarillo, se derrite y a veces huele fuerte|Se derrite y huele|Derretido',
      'Pollo Frito|Presas apanadas y crujientes|Presas apanadas|Apanado',
      'Lasaña|Pasta en capas con salsa y queso|Pasta en capas|Capas',
      'Ceviche|Pescado crudo cocido en limón|Pescado en limón|Limón',
      'Sopaipilla|Masa frita de zapallo con pebre|Frita con pebre|Pebre',
      'Churrasco|Sándwich de carne fina|Sándwich de carne|Sándwich',
      'Ramen|Fideos en caldo con huevo encima|Fideos en caldo|Fideos',
      'Paella|Arroz amarillo con mariscos en sartén|Arroz amarillo con mariscos|Sartén',
      'Tortilla|Huevo batido con papas|Huevo con papas|Huevo',
      'Panqueques|Discos dorados apilados con miel|Apilados con miel|Miel',
      'Donut|Anillo dulce con glaseado|Anillo con glaseado|Agujero',
      'Palomitas|Maíz que revienta, se come en el cine|Maíz que revienta|Cine',
      'Café|Bebida negra y amarga de la mañana|Negro y amargo|Amargo',
      'Mote con Huesillo|Trigo y durazno en jugo dulce|Trigo con durazno|Durazno',
      'Sandía|Fruta verde por fuera, roja por dentro|Verde afuera, roja adentro|Pepas'
    ]
  },
  {
    id: 'deportes',
    name: 'Deportes',
    emoji: '⚽',
    words: [
      'Fútbol|Once por lado y se juega con los pies|Once por lado, con los pies|Gol',
      'Básquetbol|Encestar en un aro a tres metros|Encestar en un aro|Aro',
      'Tenis|Raqueta, red y se grita el marcador raro|Raqueta y red|Raqueta',
      'Natación|Piscina, carriles y gorro|Piscina y carriles|Piscina',
      'Boxeo|Guantes, ring y doce asaltos|Guantes y ring|Ring',
      'Ciclismo|Bicicleta, casco y pelotón|Bicicleta y pelotón|Bicicleta',
      'Atletismo|Pista, vallas y jabalina|Pista y vallas|Pista',
      'Voleibol|Se golpea con las manos sobre una red alta|Con las manos sobre la red|Red',
      'Golf|Palo, hoyo y carrito|Palo y hoyo|Hoyo',
      'Rugby|Balón ovalado y placajes sin protección|Balón ovalado y placajes|Ovalado',
      'Béisbol|Bate, guante y se corre a las bases|Bate y bases|Bate',
      'Surf|Tabla y olas|Tabla y olas|Ola',
      'Skate|Patineta, rampas y trucos|Patineta y trucos|Patineta',
      'Ajedrez|Tablero de 64 casillas y jaque mate|Tablero y jaque mate|Jaque',
      'Karate|Artes marciales con cinturón y kata|Cinturón y kata|Cinturón',
      'Judo|Se derriba al rival agarrando el traje|Derribar agarrando el traje|Derribo',
      'Escalada|Muro, presas y arnés|Muro y arnés|Muro',
      'Patinaje|Se desliza sobre hielo dando giros|Deslizarse sobre hielo|Hielo',
      'Esquí|Se baja la montaña con dos tablas|Bajar con dos tablas|Nieve',
      'Fórmula 1|Autos de carrera y boxes|Autos de carrera y boxes|Boxes',
      'Maratón|Correr 42 kilómetros|42 kilómetros|Kilómetros',
      'Halterofilia|Levantar una barra con discos|Barra con discos|Peso',
      'Gimnasia|Barras, saltos mortales y cinta|Barras y saltos mortales|Barras',
      'Hockey|Palo curvo y disco o bocha|Palo curvo y disco|Palo',
      'Waterpolo|Se nada y se lanza a un arco|Nadar y lanzar al arco|Agua',
      'Tenis de Mesa|Paleta pequeña y pelotita blanca|Paleta y pelotita|Paleta',
      'Bádminton|Se golpea un volante con plumas|Volante con plumas|Volante',
      'Arquería|Arco, flecha y diana|Arco y diana|Diana',
      'Esgrima|Máscara blanca y espadas finas|Máscara y espadas finas|Estocada',
      'Triatlón|Nadar, pedalear y correr seguido|Tres pruebas seguidas|Tres'
    ]
  },
  {
    id: 'lugares',
    name: 'Países y Lugares',
    emoji: '🌍',
    words: [
      'París|Torre de hierro y croissants|Torre de hierro|Torre',
      'Japón|Sushi, samuráis y trenes bala|Samuráis y trenes bala|Samurái',
      'Egipto|Pirámides, faraones y el Nilo|Pirámides y faraones|Pirámide',
      'Brasil|Carnaval, samba y playas|Carnaval y samba|Carnaval',
      'Chile|Cordillera, vino y muy angosto|Cordillera y muy angosto|Angosto',
      'Argentina|Tango, mate y asado|Tango y mate|Mate',
      'México|Tacos, mariachis y picante|Mariachis y picante|Mariachi',
      'Italia|Pasta, Coliseo y góndolas|Pasta y góndolas|Pasta',
      'España|Flamenco, paella y siesta|Flamenco y paella|Flamenco',
      'China|Muralla, arroz y muchísima gente|Muralla y muchísima gente|Muralla',
      'Nueva York|Rascacielos y Estatua de la Libertad|Rascacielos y la estatua|Rascacielos',
      'Londres|Bus rojo, lluvia y Big Ben|Bus rojo y lluvia|Niebla',
      'Rusia|Frío, vodka y cúpulas de colores|Frío y cúpulas de colores|Vodka',
      'Australia|Canguros, koalas y la ópera de Sídney|Canguros y koalas|Canguro',
      'India|Curry, vacas sagradas y el Taj Mahal|Curry y vacas sagradas|Curry',
      'Alemania|Cerveza, salchichas y autos rápidos|Cerveza y autos rápidos|Cerveza',
      'Grecia|Templos blancos, mitología y mar azul|Templos y mitología|Templo',
      'Canadá|Hoja de arce, nieve y jarabe|Hoja de arce y nieve|Arce',
      'Perú|Ceviche, llamas y ruinas incas|Llamas y ruinas incas|Llama',
      'Islandia|Volcanes, géiseres y auroras|Géiseres y auroras|Aurora',
      'Machu Picchu|Ruinas incas en lo alto de un cerro|Ruinas en un cerro|Incas',
      'Amazonas|Selva enorme con un río gigante|Selva con un río gigante|Selva',
      'Sahara|Desierto de arena más famoso|Desierto de arena|Arena',
      'Everest|La montaña más alta del mundo|La montaña más alta|Cumbre',
      'Venecia|Ciudad con canales y góndolas|Ciudad con canales|Góndola',
      'Dubái|Rascacielos de lujo en el desierto|Lujo en el desierto|Lujo',
      'Hawái|Islas con volcanes, surf y collares de flores|Islas con volcanes y surf|Collar',
      'Antártica|Continente de hielo con pingüinos|Continente de hielo|Hielo',
      'Las Vegas|Casinos, luces y bodas exprés|Casinos y luces|Casino',
      'Río de Janeiro|Cristo en el cerro y playa de Copacabana|Cristo en el cerro|Cristo'
    ]
  },
  {
    id: 'profesiones',
    name: 'Profesiones',
    emoji: '👩‍⚕️',
    words: [
      'Doctor|Bata blanca, estetoscopio y recetas|Bata y estetoscopio|Bata',
      'Profesor|Pizarra, notas y sala de clases|Pizarra y notas|Pizarra',
      'Bombero|Camión rojo, manguera y escalera|Camión rojo y manguera|Manguera',
      'Policía|Patrulla, placa y esposas|Patrulla y placa|Placa',
      'Chef|Gorro alto y cocina de restaurante|Gorro alto y cocina|Gorro',
      'Abogado|Tribunal, toga y demandas|Tribunal y demandas|Tribunal',
      'Ingeniero|Cálculos, planos y obras|Cálculos y planos|Planos',
      'Programador|Escribe código frente al computador|Escribe código|Código',
      'Piloto|Cabina de avión y uniforme con galones|Cabina de avión|Cabina',
      'Enfermera|Toma la presión y pone inyecciones|Inyecciones y turnos|Inyección',
      'Arquitecto|Diseña casas y edificios|Diseña edificios|Diseño',
      'Peluquero|Tijeras, secador y sillón giratorio|Tijeras y secador|Tijeras',
      'Mecánico|Repara autos con las manos grasosas|Repara autos|Motor',
      'Dentista|Sillón reclinable y torno en la boca|Sillón y torno|Muelas',
      'Veterinario|Atiende perros y gatos enfermos|Atiende animales|Mascotas',
      'Astronauta|Traje espacial y cohete|Traje espacial y cohete|Cohete',
      'Futbolista|Cobra millones por jugar con la pelota|Le pagan por la pelota|Pelota',
      'Cantante|Micrófono, escenario y giras|Micrófono y giras|Micrófono',
      'Actor|Guion, cámara y alfombra roja|Guion y cámara|Guion',
      'Youtuber|Graba videos y vive de las visitas|Vive de las visitas|Visitas',
      'Periodista|Micrófono, notas y entrevistas|Entrevistas y notas|Entrevista',
      'Contador|Impuestos, facturas y planillas|Impuestos y planillas|Impuestos',
      'Psicólogo|Diván, escucha y sesiones semanales|Escucha en sesiones|Sesión',
      'Panadero|Amasa y hornea antes del amanecer|Amasa de madrugada|Masa',
      'Agricultor|Siembra, cosecha y tractor|Siembra y cosecha|Cosecha',
      'Pescador|Bote, red y caña|Bote, red y caña|Red',
      'Barista|Prepara café y dibuja en la espuma|Prepara café|Espuma',
      'Fotógrafo|Cámara, lente y sesiones|Cámara y lente|Lente',
      'Científico|Laboratorio, microscopio y experimentos|Laboratorio y experimentos|Laboratorio',
      'Basurero|Camión y recoge la basura de madrugada|Camión de la basura|Basura'
    ]
  },
  {
    id: 'objetos',
    name: 'Objetos de casa',
    emoji: '🏠',
    words: [
      'Refrigerador|Blanco, frío y con imanes en la puerta|Frío, con imanes|Frío',
      'Microondas|Calienta en un minuto y suena al terminar|Calienta y suena|Calienta',
      'Televisor|Pantalla grande frente al sillón|Pantalla del living|Pantalla',
      'Sofá|Mueble largo y blando del living|Mueble largo y blando|Mueble',
      'Cama|Con sábanas, donde se duerme|Con sábanas, se duerme|Sábanas',
      'Espejo|Refleja tu cara en el baño|Refleja tu cara|Reflejo',
      'Escoba|Palo con cerdas para barrer|Palo con cerdas|Barrer',
      'Lavadora|Da vueltas con la ropa sucia|Da vueltas con la ropa|Ropa',
      'Ducha|Sale agua caliente desde arriba|Agua caliente desde arriba|Agua',
      'Almohada|Blanda, bajo la cabeza|Blanda, bajo la cabeza|Blanda',
      'Reloj|Marca la hora con manecillas|Marca la hora|Hora',
      'Cortina|Tela que tapa la ventana|Tapa la ventana|Tela',
      'Lámpara|Da luz con una ampolleta|Da luz con ampolleta|Luz',
      'Ventilador|Aspas que giran y refrescan|Aspas que refrescan|Aspas',
      'Estufa|Da calor en invierno|Da calor en invierno|Calor',
      'Tostadora|Dora el pan y lo lanza|Dora el pan|Tostada',
      'Hervidor|Calienta agua y silba|Calienta agua y silba|Hervir',
      'Cuchillo|Hoja con filo para cortar|Hoja con filo|Filo',
      'Tenedor|Cubierto con cuatro puntas|Cubierto con puntas|Puntas',
      'Plato|Redondo, encima va la comida|Redondo, con la comida|Redondo',
      'Basurero|Con bolsa y tapa, para desechos|Con bolsa y tapa|Desechos',
      'Llaves|Metálicas, abren la puerta|Abren la puerta|Cerradura',
      'Control Remoto|Con botones, cambia los canales|Cambia los canales|Botones',
      'Aspiradora|Ruidosa, chupa el polvo|Chupa el polvo|Polvo',
      'Alfombra|Tela gruesa en el suelo|Tela gruesa en el suelo|Suelo',
      'Silla|Cuatro patas y respaldo|Patas y respaldo|Respaldo',
      'Ventana|Vidrio que deja ver afuera|Vidrio para ver afuera|Vidrio',
      'Puerta|Se abre con manilla y bisagras|Manilla y bisagras|Manilla',
      'Enchufe|Agujeros en la pared con electricidad|Agujeros con electricidad|Corriente',
      'Cargador|Cable que conecta el celular a la corriente|Cable a la corriente|Cable'
    ]
  },
  {
    id: 'videojuegos',
    name: 'Videojuegos',
    emoji: '🎮',
    words: [
      'Minecraft|Todo son bloques y se pica con un pico|Todo son bloques|Bloques',
      'Fortnite|Battle royale donde construyes y bailas|Battle royale con bailes|Construir',
      'Mario Bros|Plomero con bigote que salta tortugas|Plomero con bigote|Plomero',
      'Zelda|Elfo con espada que salva a la princesa|Espada y princesa|Princesa',
      'Among Us|Astronautas y hay que descubrir al impostor|Astronautas y un traidor|Nave',
      'Fall Guys|Muñequitos que compiten en obstáculos|Compiten en obstáculos|Obstáculos',
      'Roblox|Plataforma de mil juegos con monitos cuadrados|Mil juegos en uno|Monitos',
      'GTA|Robas autos en una ciudad abierta|Robar autos, ciudad abierta|Robar',
      'Call of Duty|Shooter militar en primera persona|Shooter militar|Militar',
      'League of Legends|Cinco contra cinco por destruir el nexo|Cinco contra cinco|Nexo',
      'Valorant|Shooter táctico con personajes con poderes|Shooter con habilidades|Puntería',
      'FIFA|Simulador de fútbol con equipos reales|Simulador de fútbol|Fútbol',
      'The Sims|Controlas vidas y construyes casas|Controlas vidas y casas|Vidas',
      'Tetris|Encajar piezas que caen y llenar líneas|Piezas que caen|Piezas',
      'Pac-Man|Círculo amarillo que come puntos y huye de fantasmas|Come puntos, huye de fantasmas|Fantasmas',
      'Sonic|Erizo azul que corre a toda velocidad|Erizo azul veloz|Erizo',
      'Candy Crush|Juntar dulces iguales en el celular|Juntar dulces iguales|Dulces',
      'Angry Birds|Lanzas pájaros con honda contra cerdos|Lanzar pájaros con honda|Honda',
      'Counter-Strike|Terroristas contra antiterroristas y una bomba|Bomba y rondas|Bomba',
      'Overwatch|Equipos de héroes con roles y habilidades|Héroes con roles|Héroes',
      'Elden Ring|Mundo abierto oscuro y dificilísimo|Mundo abierto dificilísimo|Difícil',
      'Dark Souls|Mueres mil veces y vuelves a la hoguera|Mueres y vuelves|Hoguera',
      'Resident Evil|Zombis y sustos en una mansión|Zombis en una mansión|Zombis',
      'Silent Hill|Pueblo con niebla y monstruos|Pueblo con niebla|Niebla',
      'Halo|Soldado con casco verde contra alienígenas|Casco verde y alienígenas|Casco',
      'God of War|Guerrero furioso y dioses griegos o nórdicos|Furia y dioses|Dioses',
      'Red Dead Redemption|Vaqueros, caballos y duelos|Vaqueros y duelos|Vaquero',
      'Mario Kart|Carreras con caparazones y cáscaras de plátano|Carreras con caparazones|Caparazón',
      'Pokémon Go|Los atrapas caminando por la calle real|Atrapar caminando|Caminar',
      'Clash Royale|Cartas para derribar las torres del rival|Cartas contra torres|Cartas'
    ]
  },
  {
    id: 'series',
    name: 'Series de TV',
    emoji: '📺',
    words: [
      'Breaking Bad|Profesor de química cocina droga|Profesor cocina droga|Química',
      'Stranger Things|Niños en bicicleta y un mundo al revés|Niños y un mundo al revés|Revés',
      'Game of Thrones|Reinos que pelean por un trono de espadas|Pelean por un trono|Trono',
      'The Office|Comedia falsa-documental en una oficina|Comedia en una oficina|Oficina',
      'Friends|Seis amigos, una cafetería y un sofá naranjo|Seis amigos y una cafetería|Cafetería',
      'La Casa de Papel|Asaltan la Fábrica de Moneda con monos rojos|Asalto con monos rojos|Atraco',
      'Dark|Un pueblo alemán y viajes en el tiempo|Pueblo y viajes en el tiempo|Cueva',
      'Black Mirror|Capítulos sueltos sobre tecnología que sale mal|Tecnología que sale mal|Tecnología',
      'The Walking Dead|Sobrevivientes en un mundo de zombis|Sobrevivir entre zombis|Zombis',
      'Los Simpsons|Familia amarilla de Springfield|Familia amarilla|Amarilla',
      'Rick y Morty|Abuelo científico y nieto viajan por dimensiones|Abuelo y nieto por dimensiones|Portal',
      'Peaky Blinders|Gánsteres ingleses con gorra y navaja|Gánsteres con gorra|Gorra',
      'Narcos|La DEA persigue a los carteles colombianos|Carteles colombianos|Carteles',
      'Chernobyl|El desastre de la central nuclear soviética|Desastre nuclear|Nuclear',
      'The Last of Us|Un hongo convierte a la gente en infectados|Hongo que infecta|Hongo',
      'Wednesday|La hija Addams en un internado|Hija Addams en un internado|Trenzas',
      'Squid Game|Juegos infantiles donde el que pierde muere|Juegos donde el que pierde muere|Juegos',
      'Vikingos|Guerreros nórdicos que saquean en barcos|Guerreros nórdicos saquean|Nórdicos',
      'Sherlock|Detective londinense que deduce todo|Detective que deduce todo|Deducción',
      'House|Médico cojo y grosero que resuelve casos raros|Médico cojo y grosero|Bastón',
      'Grey\'s Anatomy|Cirujanos que se enamoran entre operaciones|Cirujanos enamorados|Cirugía',
      'Better Call Saul|La precuela del abogado tramposo|Precuela del abogado|Abogado',
      'The Mandalorian|Cazarrecompensas con casco y un bebé verde|Casco y un bebé verde|Casco',
      'Lost|Sobrevivientes de un avión en una isla misteriosa|Avión caído en una isla|Isla',
      'Prison Break|Se hace preso para sacar a su hermano|Se hace preso para escapar|Fuga',
      'Mr. Robot|Hacker con problemas mentales derriba corporaciones|Hacker contra corporaciones|Hacker',
      'Euphoria|Adolescentes, fiestas, drogas y brillos|Adolescentes y brillos|Brillos',
      'Bridgerton|Romance en la alta sociedad inglesa antigua|Romance de época|Época',
      'Money Heist|El mismo robo español, en inglés|El mismo atraco, en inglés|Máscara',
      'Merlí|Profesor de filosofía y sus alumnos|Profesor de filosofía|Filosofía'
    ]
  },
  {
    id: 'musica',
    name: 'Música y Artistas',
    emoji: '🎵',
    words: [
      'Michael Jackson|El moonwalk y el guante blanco|Moonwalk y guante blanco|Guante',
      'The Beatles|Cuarteto de Liverpool que cruza un paso de cebra|Cuarteto de Liverpool|Cuatro',
      'Queen|Freddie Mercury y Bohemian Rhapsody|Freddie Mercury|Bohemian',
      'Shakira|Colombiana que mueve las caderas|Colombiana de caderas|Caderas',
      'Bad Bunny|Puertorriqueño de lentes raros y reguetón|Puertorriqueño de reguetón|Conejo',
      'Taylor Swift|Escribe canciones sobre sus ex y llena estadios|Canta sobre sus ex|Ex',
      'Beyoncé|Cantó en Destiny’s Child y ahora es la reina|La reina del pop|Reina',
      'Daddy Yankee|La Gasolina y el reguetón viejo|Reguetón viejo|Gasolina',
      'Coldplay|Banda británica de estadios llenos de pulseras|Banda de estadios y pulseras|Pulseras',
      'Nirvana|Grunge de los noventa y Kurt Cobain|Grunge de los noventa|Grunge',
      'Rihanna|Cantó Umbrella y después vendió maquillaje|Cantó y vendió maquillaje|Paraguas',
      'Eminem|Rapero blanco de Detroit que rapea rapidísimo|Rapero blanco velocísimo|Rapero',
      'Karol G|Colombiana de pelo teñido, "Bichota"|Colombiana de pelo teñido|Bichota',
      'Maluma|Colombiano de reguetón romántico|Reguetón romántico|Romántico',
      'Elvis Presley|El rey del rock con jopo y traje brillante|El rey del rock|Jopo',
      'Bob Marley|Rastas, Jamaica y reggae|Rastas y Jamaica|Rastas',
      'Rock|Guitarra eléctrica, batería y pelo largo|Guitarra eléctrica y batería|Eléctrica',
      'Reggaetón|Dembow, perreo y letras repetitivas|Dembow y perreo|Perreo',
      'Cumbia|Se baila en matrimonios y hay acordeón|Se baila en matrimonios|Acordeón',
      'Salsa|Se baila en pareja con vueltas y trompetas|En pareja con vueltas|Pareja',
      'Jazz|Saxofón, contrabajo e improvisación|Saxofón e improvisación|Saxofón',
      'Ópera|Cantantes lírico con voz potentísima y sin micrófono|Voz potente sin micrófono|Lírico',
      'Guitarra|Seis cuerdas y se rasguea|Seis cuerdas, se rasguea|Cuerdas',
      'Piano|Teclas blancas y negras|Teclas blancas y negras|Teclas',
      'Batería|Bombo, platillos y baquetas|Bombo y baquetas|Baquetas',
      'Violín|Se apoya en el hombro y se toca con arco|Se toca con arco|Arco',
      'Karaoke|Cantas leyendo la letra en pantalla|Cantar leyendo la letra|Letra',
      'Concierto|Estadio lleno, luces y la banda en vivo|Estadio lleno en vivo|Estadio',
      'Spotify|App verde de playlists|App verde de playlists|Playlist',
      'Audífonos|Se ponen en las orejas para escuchar solo|En las orejas, escuchas solo|Orejas'
    ]
  },
  {
    id: 'superheroes',
    name: 'Superhéroes',
    emoji: '🦸',
    words: [
      'Superman|Capa roja, vuela y es de Kriptón|Capa roja y vuela|Capa',
      'Batman|Millonario de negro con batimóvil|Millonario de negro|Batimóvil',
      'Spider-Man|Lanza telarañas y trepa edificios|Lanza telarañas|Telaraña',
      'Iron Man|Millonario dentro de una armadura roja y dorada|Armadura roja y dorada|Armadura',
      'Hulk|Se pone verde y gigante cuando se enoja|Verde cuando se enoja|Verde',
      'Thor|Dios nórdico con martillo y rayos|Martillo y rayos|Martillo',
      'Capitán América|Escudo con estrella y suero de supersoldado|Escudo con estrella|Escudo',
      'Wonder Woman|Amazona con lazo dorado y brazaletes|Amazona con lazo|Lazo',
      'Flash|Corre más rápido que nadie, de rojo|Corre rapidísimo, de rojo|Velocidad',
      'Aquaman|Habla con los peces y manda en la Atlántida|Manda bajo el mar|Tridente',
      'Black Panther|Rey de Wakanda con traje de vibranium|Rey de Wakanda|Wakanda',
      'Deadpool|Traje rojo, no se muere y no para de hablar|Rojo y no para de hablar|Bocón',
      'Wolverine|Garras de metal y patillas|Garras de metal|Garras',
      'Doctor Strange|Capa roja, portales y magia|Portales y magia|Portal',
      'Loki|Hermano tramposo de Thor, dios del engaño|Hermano tramposo de Thor|Engaño',
      'Thanos|Morado, guantelete y chasquido|Guantelete y chasquido|Chasquido',
      'Joker|Villano payaso de pelo verde|Villano payaso|Payaso',
      'Venom|Simbionte negro con lengua larga|Simbionte negro|Simbionte',
      'Ant-Man|Encoge hasta el tamaño de una hormiga|Encoge de tamaño|Encoger',
      'Groot|Árbol que solo dice su propio nombre|Árbol de pocas palabras|Árbol',
      'Rocket|Mapache que dispara armas enormes|Mapache armado|Mapache',
      'Star-Lord|Lidera a los Guardianes con su walkman|Guardianes y su walkman|Walkman',
      'Robin|El ayudante joven de Batman|El ayudante de Batman|Ayudante',
      'Catwoman|Ladrona con traje de gato y látigo|Ladrona con látigo|Látigo',
      'Green Lantern|Anillo verde que crea lo que imagina|Anillo verde que crea|Anillo',
      'Profesor X|Telépata calvo en silla de ruedas|Telépata en silla de ruedas|Telépata',
      'Magneto|Controla el metal y odia a los humanos|Controla el metal|Metal',
      'Viuda Negra|Espía rusa pelirroja sin poderes|Espía pelirroja|Espía',
      'Ojo de Halcón|Arquero de los Vengadores que nunca falla|Arquero que nunca falla|Arco',
      'Shazam|Un niño que dice una palabra y se hace adulto|Niño que se hace adulto|Rayo'
    ]
  }
];

const CATEGORIES = RAW.map((cat) => ({
  id: cat.id,
  name: cat.name,
  emoji: cat.emoji,
  words: cat.words.map((entry) => {
    const [word, facil, media, dificil] = entry.split('|');
    return {
      word: word.trim(),
      hints: {
        facil: (facil || '').trim(),
        media: (media || facil || '').trim(),
        dificil: (dificil || media || facil || '').trim()
      }
    };
  })
}));

/** Metadata liviana para el cliente (sin revelar las palabras). */
const CATEGORY_INDEX = CATEGORIES.map((c) => ({
  id: c.id,
  name: c.name,
  emoji: c.emoji,
  count: c.words.length
}));

const CATEGORY_BY_ID = new Map(CATEGORIES.map((c) => [c.id, c]));

/** Niveles de pista, del más generoso al más seco. */
const HINT_LEVELS = [
  { id: 'facil', name: 'Fácil', desc: 'Una descripción completa' },
  { id: 'media', name: 'Media', desc: 'Solo un par de señas' },
  { id: 'dificil', name: 'Difícil', desc: 'Una sola palabra' }
];
const HINT_LEVEL_IDS = HINT_LEVELS.map((l) => l.id);

module.exports = { CATEGORIES, CATEGORY_INDEX, CATEGORY_BY_ID, HINT_LEVELS, HINT_LEVEL_IDS };
