'use strict';

/**
 * Banco de palabras por categoría.
 * Formato de cada entrada: "Palabra|pista para el impostor"
 * La pista es vaga a propósito: orienta sin delatar la palabra exacta.
 */

const RAW = [
  {
    id: 'peliculas',
    name: 'Películas',
    emoji: '🎬',
    words: [
      'Titanic|Un barco enorme choca con un iceberg',
      'El Padrino|Una familia de la mafia italiana',
      'Jurassic Park|Un parque lleno de dinosaurios',
      'Matrix|Descubre que el mundo es una simulación',
      'Rápidos y Furiosos|Autos tuneados y carreras ilegales',
      'Shrek|Un ogro verde que vive en un pantano',
      'Toy Story|Los juguetes cobran vida sin el niño',
      'Avatar|Alienígenas azules altos en otro planeta',
      'Harry Potter|Un niño mago con lentes y cicatriz',
      'El Señor de los Anillos|Hay que destruir un anillo en un volcán',
      'Star Wars|Espadas láser y una galaxia lejana',
      'Rey León|Un cachorro que debe heredar la selva',
      'Frozen|Una reina que congela todo lo que toca',
      'Coco|Un niño viaja al mundo de los muertos',
      'Batman|Millonario disfrazado de murciélago',
      'Spider-Man|Lo picó una araña y trepa paredes',
      'Joker|El payaso que se ríe y da miedo',
      'Parasite|Una familia pobre se infiltra en una rica',
      'El Resplandor|Un hotel vacío enloquece al papá',
      'Tiburón|Un escualo gigante ataca bañistas',
      'Volver al Futuro|Viaja al pasado en un auto',
      'Forrest Gump|Corre por todo el país sin parar',
      'Gladiador|Un romano pelea en el Coliseo',
      'Interstellar|Buscan otro planeta para la humanidad',
      'Piratas del Caribe|Tesoros, barcos y un capitán borracho con rastas',
      'Los Vengadores|Un equipo enorme de superhéroes',
      'Rocky|Un boxeador entrena subiendo escaleras',
      'E.T.|Un extraterrestre quiere volver a su casa',
      'La La Land|Bailan y cantan en Los Ángeles',
      'Intensamente|Las emociones viven dentro de una niña'
    ]
  },
  {
    id: 'animales',
    name: 'Animales',
    emoji: '🐾',
    words: [
      'Elefante|Gris, gigante, con trompa y colmillos',
      'Jirafa|El cuello más largo de todos',
      'Pingüino|Ave que no vuela y camina en el hielo',
      'Tiburón|Aleta que asoma en el mar',
      'Águila|Ave de rapiña que ve desde muy alto',
      'Cocodrilo|Reptil de río con mandíbula enorme',
      'Serpiente|Se arrastra y algunas tienen veneno',
      'Perro|Ladra y mueve la cola',
      'Gato|Maúlla y siempre cae de pie',
      'Caballo|Se monta y galopa',
      'León|Melena y ruge en la sabana',
      'Tigre|Naranjo con rayas negras',
      'Oso|Grande, peludo e hiberna',
      'Mono|Se cuelga de los árboles y come plátanos',
      'Delfín|Salta en el mar y es muy listo',
      'Ballena|El animal más grande del océano',
      'Murciélago|Cuelga de cabeza y vuela de noche',
      'Búho|Ojos enormes y gira la cabeza',
      'Abeja|Hace miel y pica',
      'Hormiga|Diminuta y carga más que su peso',
      'Araña|Ocho patas y teje telas',
      'Camello|Joroba y cruza el desierto',
      'Canguro|Salta y lleva la cría en la bolsa',
      'Koala|Se abraza a los árboles y duerme todo el día',
      'Zorro|Naranjo, astuto y de cola peluda',
      'Lobo|Aúlla a la luna y anda en manada',
      'Rana|Verde, salta y croa',
      'Tortuga|Camina lentísimo con su caparazón',
      'Pulpo|Ocho tentáculos y suelta tinta',
      'Flamenco|Rosado y se para en una pata'
    ]
  },
  {
    id: 'anime',
    name: 'Anime',
    emoji: '🍥',
    words: [
      'Naruto|Ninja rubio que quiere ser Hokage',
      'Dragon Ball|Buscan siete esferas y se ponen rubios',
      'One Piece|Piratas buscando el tesoro más grande',
      'Attack on Titan|Gigantes que comen gente tras los muros',
      'Death Note|Un cuaderno que mata a quien escribas',
      'Demon Slayer|Cazan criaturas nocturnas con espadas japonesas',
      'My Hero Academia|Escuela donde todos tienen superpoderes',
      'Pokémon|Atrapa criaturas en bolitas rojas',
      'Sailor Moon|Chicas que se transforman con la luna',
      'Evangelion|Adolescentes pilotean robots gigantes',
      'Fullmetal Alchemist|Dos hermanos alquimistas, uno es armadura',
      'Jujutsu Kaisen|Estudiantes que pelean contra maldiciones',
      'Bleach|Segador de almas con espada gigante',
      'Tokyo Ghoul|Se convierte en algo que come humanos',
      'Hunter x Hunter|Un niño busca a su papá cazador',
      'Cowboy Bebop|Cazarrecompensas en una nave espacial',
      'Chainsaw Man|Un chico con motosierras en la cabeza',
      'Spy x Family|Un espía finge tener familia',
      'Haikyuu|Vóleibol de secundaria y un chico bajito',
      'Slam Dunk|Básquetbol japonés y un pelirrojo',
      'Inuyasha|Chica cae a un pozo y viaja al Japón feudal',
      'Digimon|Niños con monstruos digitales',
      'Doraemon|Gato robot azul con bolsillo mágico',
      'Shingeki no Kyojin|Titanes que rompen las murallas',
      'Your Name|Dos jóvenes intercambian cuerpos',
      'El viaje de Chihiro|Niña atrapada en unos baños de espíritus',
      'Mi vecino Totoro|Criatura gris gigante y un gato-bus',
      'Steins;Gate|Un microondas manda mensajes al pasado',
      'Code Geass|Príncipe exiliado con poder de dar órdenes',
      'Berserk|Guerrero con una espada descomunal'
    ]
  },
  {
    id: 'comida',
    name: 'Comida',
    emoji: '🍕',
    words: [
      'Pizza|Redonda, con queso y se corta en triángulos',
      'Hamburguesa|Carne y verduras entre dos panes',
      'Sushi|Arroz y pescado crudo enrollado en alga',
      'Tacos|Tortilla doblada con carne y limón',
      'Empanada|Masa horneada rellena de carne',
      'Asado|Carne a la parrilla con amigos',
      'Completo|Vienesa con palta, tomate y mayonesa',
      'Pastel|Dulce de cumpleaños con velas',
      'Helado|Frío, dulce y en cono',
      'Chocolate|Barra dulce de cacao',
      'Ensalada|Lechuga, tomate y poco más',
      'Sopa|Caldo caliente que se toma con cuchara',
      'Arroz|Granos blancos que acompañan todo',
      'Papas Fritas|Bastoncitos crujientes con ketchup',
      'Pan|Se hornea, se corta en rebanadas',
      'Queso|Amarillo, se derrite y a veces huele fuerte',
      'Pollo Frito|Presas apanadas y crujientes',
      'Lasaña|Pasta en capas con salsa y queso',
      'Ceviche|Pescado crudo cocido en limón',
      'Sopaipilla|Masa frita de zapallo con pebre',
      'Churrasco|Sándwich de carne fina',
      'Ramen|Fideos en caldo con huevo encima',
      'Paella|Arroz amarillo con mariscos en sartén',
      'Tortilla|Huevo batido con papas',
      'Panqueques|Discos dorados apilados con miel',
      'Donut|Anillo dulce con glaseado',
      'Palomitas|Maíz que revienta, se come en el cine',
      'Café|Bebida negra y amarga de la mañana',
      'Mote con Huesillo|Trigo y durazno en jugo dulce',
      'Sandía|Fruta verde por fuera, roja por dentro'
    ]
  },
  {
    id: 'deportes',
    name: 'Deportes',
    emoji: '⚽',
    words: [
      'Fútbol|Once por lado y se juega con los pies',
      'Básquetbol|Encestar en un aro a tres metros',
      'Tenis|Raqueta, red y se grita el marcador raro',
      'Natación|Piscina, carriles y gorro',
      'Boxeo|Guantes, ring y doce asaltos',
      'Ciclismo|Bicicleta, casco y pelotón',
      'Atletismo|Pista, vallas y jabalina',
      'Voleibol|Se golpea con las manos sobre una red alta',
      'Golf|Palo, hoyo y carrito',
      'Rugby|Balón ovalado y placajes sin protección',
      'Béisbol|Bate, guante y se corre a las bases',
      'Surf|Tabla y olas',
      'Skate|Patineta, rampas y trucos',
      'Ajedrez|Tablero de 64 casillas y jaque mate',
      'Karate|Artes marciales con cinturón y kata',
      'Judo|Se derriba al rival agarrando el traje',
      'Escalada|Muro, presas y arnés',
      'Patinaje|Se desliza sobre hielo dando giros',
      'Esquí|Se baja la montaña con dos tablas',
      'Fórmula 1|Autos de carrera y boxes',
      'Maratón|Correr 42 kilómetros',
      'Halterofilia|Levantar una barra con discos',
      'Gimnasia|Barras, saltos mortales y cinta',
      'Hockey|Palo curvo y disco o bocha',
      'Waterpolo|Se nada y se lanza a un arco',
      'Tenis de Mesa|Paleta pequeña y pelotita blanca',
      'Bádminton|Se golpea un volante con plumas',
      'Arquería|Arco, flecha y diana',
      'Esgrima|Máscara blanca y espadas finas',
      'Triatlón|Nadar, pedalear y correr seguido'
    ]
  },
  {
    id: 'lugares',
    name: 'Países y Lugares',
    emoji: '🌍',
    words: [
      'París|Torre de hierro y croissants',
      'Japón|Sushi, samuráis y trenes bala',
      'Egipto|Pirámides, faraones y el Nilo',
      'Brasil|Carnaval, samba y playas',
      'Chile|Cordillera, vino y muy angosto',
      'Argentina|Tango, mate y asado',
      'México|Tacos, mariachis y picante',
      'Italia|Pasta, Coliseo y góndolas',
      'España|Flamenco, paella y siesta',
      'China|Muralla, arroz y muchísima gente',
      'Nueva York|Rascacielos y Estatua de la Libertad',
      'Londres|Bus rojo, lluvia y Big Ben',
      'Rusia|Frío, vodka y cúpulas de colores',
      'Australia|Canguros, koalas y la ópera de Sídney',
      'India|Curry, vacas sagradas y el Taj Mahal',
      'Alemania|Cerveza, salchichas y autos rápidos',
      'Grecia|Templos blancos, mitología y mar azul',
      'Canadá|Hoja de arce, nieve y jarabe',
      'Perú|Ceviche, llamas y ruinas incas',
      'Islandia|Volcanes, géiseres y auroras',
      'Machu Picchu|Ruinas incas en lo alto de un cerro',
      'Amazonas|Selva enorme con un río gigante',
      'Sahara|Desierto de arena más famoso',
      'Everest|La montaña más alta del mundo',
      'Venecia|Ciudad con canales y góndolas',
      'Dubái|Rascacielos de lujo en el desierto',
      'Hawái|Islas con volcanes, surf y collares de flores',
      'Antártica|Continente de hielo con pingüinos',
      'Las Vegas|Casinos, luces y bodas exprés',
      'Río de Janeiro|Cristo en el cerro y playa de Copacabana'
    ]
  },
  {
    id: 'profesiones',
    name: 'Profesiones',
    emoji: '👩‍⚕️',
    words: [
      'Doctor|Bata blanca, estetoscopio y recetas',
      'Profesor|Pizarra, notas y sala de clases',
      'Bombero|Camión rojo, manguera y escalera',
      'Policía|Patrulla, placa y esposas',
      'Chef|Gorro alto y cocina de restaurante',
      'Abogado|Tribunal, toga y demandas',
      'Ingeniero|Cálculos, planos y obras',
      'Programador|Escribe código frente al computador',
      'Piloto|Cabina de avión y uniforme con galones',
      'Enfermera|Toma la presión y pone inyecciones',
      'Arquitecto|Diseña casas y edificios',
      'Peluquero|Tijeras, secador y sillón giratorio',
      'Mecánico|Repara autos con las manos grasosas',
      'Dentista|Sillón reclinable y torno en la boca',
      'Veterinario|Atiende perros y gatos enfermos',
      'Astronauta|Traje espacial y cohete',
      'Futbolista|Cobra millones por jugar con la pelota',
      'Cantante|Micrófono, escenario y giras',
      'Actor|Guion, cámara y alfombra roja',
      'Youtuber|Graba videos y vive de las visitas',
      'Periodista|Micrófono, notas y entrevistas',
      'Contador|Impuestos, facturas y planillas',
      'Psicólogo|Diván, escucha y sesiones semanales',
      'Panadero|Amasa y hornea antes del amanecer',
      'Agricultor|Siembra, cosecha y tractor',
      'Pescador|Bote, red y caña',
      'Barista|Prepara café y dibuja en la espuma',
      'Fotógrafo|Cámara, lente y sesiones',
      'Científico|Laboratorio, microscopio y experimentos',
      'Basurero|Camión y recoge la basura de madrugada'
    ]
  },
  {
    id: 'objetos',
    name: 'Objetos de casa',
    emoji: '🏠',
    words: [
      'Refrigerador|Blanco, frío y con imanes en la puerta',
      'Microondas|Calienta en un minuto y suena al terminar',
      'Televisor|Pantalla grande frente al sillón',
      'Sofá|Mueble largo y blando del living',
      'Cama|Con sábanas, donde se duerme',
      'Espejo|Refleja tu cara en el baño',
      'Escoba|Palo con cerdas para barrer',
      'Lavadora|Da vueltas con la ropa sucia',
      'Ducha|Sale agua caliente desde arriba',
      'Almohada|Blanda, bajo la cabeza',
      'Reloj|Marca la hora con manecillas',
      'Cortina|Tela que tapa la ventana',
      'Lámpara|Da luz con una ampolleta',
      'Ventilador|Aspas que giran y refrescan',
      'Estufa|Da calor en invierno',
      'Tostadora|Dora el pan y lo lanza',
      'Hervidor|Calienta agua y silba',
      'Cuchillo|Hoja con filo para cortar',
      'Tenedor|Cubierto con cuatro puntas',
      'Plato|Redondo, encima va la comida',
      'Basurero|Con bolsa y tapa, para desechos',
      'Llaves|Metálicas, abren la puerta',
      'Control Remoto|Con botones, cambia los canales',
      'Aspiradora|Ruidosa, chupa el polvo',
      'Alfombra|Tela gruesa en el suelo',
      'Silla|Cuatro patas y respaldo',
      'Ventana|Vidrio que deja ver afuera',
      'Puerta|Se abre con manilla y bisagras',
      'Enchufe|Agujeros en la pared con electricidad',
      'Cargador|Cable que conecta el celular a la corriente'
    ]
  },
  {
    id: 'videojuegos',
    name: 'Videojuegos',
    emoji: '🎮',
    words: [
      'Minecraft|Todo son bloques y se pica con un pico',
      'Fortnite|Battle royale donde construyes y bailas',
      'Mario Bros|Plomero con bigote que salta tortugas',
      'Zelda|Elfo con espada que salva a la princesa',
      'Among Us|Astronautas y hay que descubrir al impostor',
      'Fall Guys|Muñequitos que compiten en obstáculos',
      'Roblox|Plataforma de mil juegos con monitos cuadrados',
      'GTA|Robas autos en una ciudad abierta',
      'Call of Duty|Shooter militar en primera persona',
      'League of Legends|Cinco contra cinco por destruir el nexo',
      'Valorant|Shooter táctico con personajes con poderes',
      'FIFA|Simulador de fútbol con equipos reales',
      'The Sims|Controlas vidas y construyes casas',
      'Tetris|Encajar piezas que caen y llenar líneas',
      'Pac-Man|Círculo amarillo que come puntos y huye de fantasmas',
      'Sonic|Erizo azul que corre a toda velocidad',
      'Candy Crush|Juntar dulces iguales en el celular',
      'Angry Birds|Lanzas pájaros con honda contra cerdos',
      'Counter-Strike|Terroristas contra antiterroristas y una bomba',
      'Overwatch|Equipos de héroes con roles y habilidades',
      'Elden Ring|Mundo abierto oscuro y dificilísimo',
      'Dark Souls|Mueres mil veces y vuelves a la hoguera',
      'Resident Evil|Zombis y sustos en una mansión',
      'Silent Hill|Pueblo con niebla y monstruos',
      'Halo|Soldado con casco verde contra alienígenas',
      'God of War|Guerrero furioso y dioses griegos o nórdicos',
      'Red Dead Redemption|Vaqueros, caballos y duelos',
      'Mario Kart|Carreras con caparazones y cáscaras de plátano',
      'Pokémon Go|Los atrapas caminando por la calle real',
      'Clash Royale|Cartas para derribar las torres del rival'
    ]
  },
  {
    id: 'series',
    name: 'Series de TV',
    emoji: '📺',
    words: [
      'Breaking Bad|Profesor de química cocina droga',
      'Stranger Things|Niños en bicicleta y un mundo al revés',
      'Game of Thrones|Reinos que pelean por un trono de espadas',
      'The Office|Comedia falsa-documental en una oficina',
      'Friends|Seis amigos, una cafetería y un sofá naranjo',
      'La Casa de Papel|Asaltan la Fábrica de Moneda con monos rojos',
      'Dark|Un pueblo alemán y viajes en el tiempo',
      'Black Mirror|Capítulos sueltos sobre tecnología que sale mal',
      'The Walking Dead|Sobrevivientes en un mundo de zombis',
      'Los Simpsons|Familia amarilla de Springfield',
      'Rick y Morty|Abuelo científico y nieto viajan por dimensiones',
      'Peaky Blinders|Gánsteres ingleses con gorra y navaja',
      'Narcos|La DEA persigue a los carteles colombianos',
      'Chernobyl|El desastre de la central nuclear soviética',
      'The Last of Us|Un hongo convierte a la gente en infectados',
      'Wednesday|La hija Addams en un internado',
      'Squid Game|Juegos infantiles donde el que pierde muere',
      'Vikingos|Guerreros nórdicos que saquean en barcos',
      'Sherlock|Detective londinense que deduce todo',
      'House|Médico cojo y grosero que resuelve casos raros',
      'Grey\'s Anatomy|Cirujanos que se enamoran entre operaciones',
      'Better Call Saul|La precuela del abogado tramposo',
      'The Mandalorian|Cazarrecompensas con casco y un bebé verde',
      'Lost|Sobrevivientes de un avión en una isla misteriosa',
      'Prison Break|Se hace preso para sacar a su hermano',
      'Mr. Robot|Hacker con problemas mentales derriba corporaciones',
      'Euphoria|Adolescentes, fiestas, drogas y brillos',
      'Bridgerton|Romance en la alta sociedad inglesa antigua',
      'Money Heist|El mismo robo español, en inglés',
      'Merlí|Profesor de filosofía y sus alumnos'
    ]
  },
  {
    id: 'musica',
    name: 'Música y Artistas',
    emoji: '🎵',
    words: [
      'Michael Jackson|El moonwalk y el guante blanco',
      'The Beatles|Cuarteto de Liverpool que cruza un paso de cebra',
      'Queen|Freddie Mercury y Bohemian Rhapsody',
      'Shakira|Colombiana que mueve las caderas',
      'Bad Bunny|Puertorriqueño de lentes raros y reguetón',
      'Taylor Swift|Escribe canciones sobre sus ex y llena estadios',
      'Beyoncé|Cantó en Destiny’s Child y ahora es la reina',
      'Daddy Yankee|La Gasolina y el reguetón viejo',
      'Coldplay|Banda británica de estadios llenos de pulseras',
      'Nirvana|Grunge de los noventa y Kurt Cobain',
      'Rihanna|Cantó Umbrella y después vendió maquillaje',
      'Eminem|Rapero blanco de Detroit que rapea rapidísimo',
      'Karol G|Colombiana de pelo teñido, "Bichota"',
      'Maluma|Colombiano de reguetón romántico',
      'Elvis Presley|El rey del rock con jopo y traje brillante',
      'Bob Marley|Rastas, Jamaica y reggae',
      'Rock|Guitarra eléctrica, batería y pelo largo',
      'Reggaetón|Dembow, perreo y letras repetitivas',
      'Cumbia|Se baila en matrimonios y hay acordeón',
      'Salsa|Se baila en pareja con vueltas y trompetas',
      'Jazz|Saxofón, contrabajo e improvisación',
      'Ópera|Cantantes lírico con voz potentísima y sin micrófono',
      'Guitarra|Seis cuerdas y se rasguea',
      'Piano|Teclas blancas y negras',
      'Batería|Bombo, platillos y baquetas',
      'Violín|Se apoya en el hombro y se toca con arco',
      'Karaoke|Cantas leyendo la letra en pantalla',
      'Concierto|Estadio lleno, luces y la banda en vivo',
      'Spotify|App verde de playlists',
      'Audífonos|Se ponen en las orejas para escuchar solo'
    ]
  },
  {
    id: 'superheroes',
    name: 'Superhéroes',
    emoji: '🦸',
    words: [
      'Superman|Capa roja, vuela y es de Kriptón',
      'Batman|Millonario de negro con batimóvil',
      'Spider-Man|Lanza telarañas y trepa edificios',
      'Iron Man|Millonario dentro de una armadura roja y dorada',
      'Hulk|Se pone verde y gigante cuando se enoja',
      'Thor|Dios nórdico con martillo y rayos',
      'Capitán América|Escudo con estrella y suero de supersoldado',
      'Wonder Woman|Amazona con lazo dorado y brazaletes',
      'Flash|Corre más rápido que nadie, de rojo',
      'Aquaman|Habla con los peces y manda en la Atlántida',
      'Black Panther|Rey de Wakanda con traje de vibranium',
      'Deadpool|Traje rojo, no se muere y no para de hablar',
      'Wolverine|Garras de metal y patillas',
      'Doctor Strange|Capa roja, portales y magia',
      'Loki|Hermano tramposo de Thor, dios del engaño',
      'Thanos|Morado, guantelete y chasquido',
      'Joker|Villano payaso de pelo verde',
      'Venom|Simbionte negro con lengua larga',
      'Ant-Man|Encoge hasta el tamaño de una hormiga',
      'Groot|Árbol que solo dice su propio nombre',
      'Rocket|Mapache que dispara armas enormes',
      'Star-Lord|Lidera a los Guardianes con su walkman',
      'Robin|El ayudante joven de Batman',
      'Catwoman|Ladrona con traje de gato y látigo',
      'Green Lantern|Anillo verde que crea lo que imagina',
      'Profesor X|Telépata calvo en silla de ruedas',
      'Magneto|Controla el metal y odia a los humanos',
      'Viuda Negra|Espía rusa pelirroja sin poderes',
      'Ojo de Halcón|Arquero de los Vengadores que nunca falla',
      'Shazam|Un niño que dice una palabra y se hace adulto'
    ]
  }
];

const CATEGORIES = RAW.map((cat) => ({
  id: cat.id,
  name: cat.name,
  emoji: cat.emoji,
  words: cat.words.map((entry) => {
    const [word, hint] = entry.split('|');
    return { word: word.trim(), hint: (hint || '').trim() };
  })
}));

/** Metadata liviana para el cliente (sin revelar las palabras). */
const CATEGORY_INDEX = CATEGORIES.map((c) => ({
  id: c.id,
  name: c.name,
  emoji: c.emoji,
  count: c.words.length
}));

const CATEGORY_BY_ID = new Map(CATEGORIES.map((c) => [c.id, c]));

module.exports = { CATEGORIES, CATEGORY_INDEX, CATEGORY_BY_ID };
