'use strict';

/**
 * Banco de palabras por categoría.
 *
 * Formato: "Palabra|pista fácil|pista media|pista difícil"
 *
 * Los tres niveles van de más a menos información. Ninguno nombra la palabra:
 *   Karate | "Artes marciales con cinturón y kata" | "Cinturón y kata" | "Cinturón"
 */

const RAW = [
  {
    id: 'peliculas',
    name: 'Películas',
    emoji: '🎬',
    words: [
      'Titanic|Un viaje de lujo que acaba en tragedia|Lujo y tragedia|Naufragio',
      'El Padrino|El poder se hereda dentro de la familia|Poder que se hereda|Familia',
      'Jurassic Park|Revivir algo que se extinguió sale caro|Revivir lo extinto|Extinción',
      'Matrix|Nada de lo que ves es real|Nada es real|Ilusión',
      'Rápidos y Furiosos|Velocidad, familia y mucho motor|Velocidad y familia|Motores',
      'Shrek|El feo resulta ser el bueno|El feo es el bueno|Pantano',
      'Toy Story|Lo que pasa cuando no estás mirando|Cuando no miras|Infancia',
      'Avatar|Colonizar un mundo que no es tuyo|Colonizar otro mundo|Selva',
      'Harry Potter|Un huérfano descubre que es especial|Huérfano especial|Escuela',
      'El Señor de los Anillos|Un objeto pequeño corrompe a cualquiera|Un objeto corrompe|Viaje',
      'Star Wars|Padres, hijos y una guerra muy antigua|Padres e hijos en guerra|Galaxia',
      'Rey León|Un hijo huye y vuelve a reclamar lo suyo|Huye y vuelve por lo suyo|Sucesión',
      'Frozen|Dos hermanas y un poder difícil de contener|Poder difícil de contener|Hermanas',
      'Coco|La familia importa incluso después de morir|La familia tras la muerte|Recuerdo',
      'Batman|Sin poderes, pero con mucho dinero y trauma|Dinero y trauma|Venganza',
      'Spider-Man|Un adolescente aprende lo que cuesta el deber|Lo que cuesta el deber|Responsabilidad',
      'Joker|Cómo la sociedad fabrica a un villano|Cómo se fabrica un villano|Locura',
      'Parasite|Los de abajo se cuelan en la casa de arriba|Los de abajo se cuelan|Clases',
      'El Resplandor|El aislamiento vuelve loco a un padre|El aislamiento enloquece|Encierro',
      'Tiburón|Un pueblo costero deja de meterse al mar|Nadie se mete al mar|Miedo',
      'Volver al Futuro|Tocar el pasado desordena el presente|Tocar el pasado|Tiempo',
      'Forrest Gump|Un ingenuo termina viviéndolo todo|Un ingenuo lo vive todo|Suerte',
      'Gladiador|Un general esclavizado busca su venganza|Esclavizado busca venganza|Arena',
      'Interstellar|Un padre se va lejísimos para salvar a su hija|Un padre se va lejísimos|Espacio',
      'Piratas del Caribe|Botín, maldiciones y un capitán poco fiable|Botín y maldiciones|Mar',
      'Los Vengadores|Egos enormes obligados a trabajar juntos|Egos obligados a juntarse|Equipo',
      'Rocky|Un don nadie aguanta de pie hasta el final|Un don nadie aguanta|Perseverancia',
      'E.T.|Un niño esconde a alguien que quiere irse a casa|Alguien quiere volver a casa|Amistad',
      'La La Land|Perseguir el sueño cuesta el amor|El sueño cuesta el amor|Sueños',
      'Intensamente|Lo que ocurre dentro de tu cabeza|Dentro de tu cabeza|Emociones'
    ]
  },
  {
    id: 'animales',
    name: 'Animales',
    emoji: '🐾',
    words: [
      'Elefante|El más grande que camina por tierra|El más grande de tierra|Gigante',
      'Jirafa|Alcanza lo que nadie más alcanza|Alcanza lo que nadie|Altura',
      'Pingüino|Ave de frío extremo que no despega|Ave de frío que no vuela|Antártica',
      'Tiburón|Depredador que vacía una playa|Vacía una playa|Depredador',
      'Águila|Caza desde lo alto y no falla|Caza desde lo alto|Vista',
      'Cocodrilo|Espera quieto en el agua y ataca de golpe|Espera quieto y ataca|Emboscada',
      'Serpiente|Avanza sin extremidades y da miedo|Avanza sin extremidades|Veneno',
      'Perro|El compañero más leal que existe|El más leal|Lealtad',
      'Gato|Vive contigo pero manda él|Vive contigo pero manda él|Independiente',
      'Caballo|Nos movió durante siglos|Nos movió siglos|Galope',
      'León|El que manda en la sabana|Manda en la sabana|Realeza',
      'Tigre|Caza solo y en silencio|Caza solo y en silencio|Sigilo',
      'Oso|Enorme, peludo y duerme el invierno|Enorme y duerme el invierno|Hibernación',
      'Mono|Nuestro pariente más cercano|Nuestro pariente cercano|Evolución',
      'Delfín|Del mar y sorprendentemente listo|Del mar y muy listo|Inteligencia',
      'Ballena|El animal más grande del planeta|El más grande del planeta|Inmenso',
      'Murciélago|Se orienta a oscuras sin ver|Se orienta a oscuras|Nocturno',
      'Búho|Trabaja de noche y gira el cuello|Trabaja de noche|Sabiduría',
      'Abeja|Trabaja para la colmena y sacrifica la vida al picar|Muere al defenderse|Colmena',
      'Hormiga|Minúscula y carga muchísimo más que ella|Carga más que su peso|Trabajo',
      'Araña|Ocho patas y fabrica su propia trampa|Fabrica su propia trampa|Trampa',
      'Camello|Cruza la sequía sin beber|Cruza la sequía|Desierto',
      'Canguro|Se desplaza a saltos y lleva la cría encima|Lleva la cría encima|Salto',
      'Koala|Australiano que duerme casi todo el día|Australiano dormilón|Pereza',
      'Zorro|Tiene fama de listo y ladrón|Fama de listo y ladrón|Astucia',
      'Lobo|Caza en grupo y aúlla de noche|Caza en grupo|Manada',
      'Rana|Vive entre el agua y la tierra|Entre el agua y la tierra|Anfibio',
      'Tortuga|Va lentísima y carga su casa|Lentísima y carga su casa|Lentitud',
      'Pulpo|Muchos brazos y escapa por cualquier hueco|Escapa por cualquier hueco|Tentáculos',
      'Flamenco|Rosado y descansa a media pata|Descansa a media pata|Equilibrio'
    ]
  },
  {
    id: 'anime',
    name: 'Anime',
    emoji: '🍥',
    words: [
      'Naruto|Un huérfano rechazado quiere ser el jefe del pueblo|Rechazado quiere liderar|Constancia',
      'Dragon Ball|Cada pelea sube el poder un nivel más|Cada pelea sube un nivel|Torneo',
      'One Piece|Una tripulación busca el tesoro definitivo|Buscan el tesoro definitivo|Tripulación',
      'Attack on Titan|La humanidad vive encerrada por miedo|Encerrados por miedo|Murallas',
      'Death Note|Un estudiante decide quién merece morir|Decide quién merece morir|Justicia',
      'Demon Slayer|Un hermano lucha por salvar a su hermana|Lucha por salvar a su hermana|Hermandad',
      'My Hero Academia|Un chico sin don entra a la mejor escuela|Sin don entra a la mejor escuela|Vocación',
      'Pokémon|Coleccionar criaturas y hacerlas pelear|Coleccionar y hacer pelear|Coleccionar',
      'Sailor Moon|Chicas comunes que se transforman en guerreras|Comunes que se vuelven guerreras|Transformación',
      'Evangelion|Adolescentes rotos peleando contra lo desconocido|Adolescentes rotos|Angustia',
      'Fullmetal Alchemist|Dos hermanos pagan carísimo un intento de resucitar|Pagan caro resucitar|Equivalencia',
      'Jujutsu Kaisen|Estudiantes exorcizan lo que nace del miedo humano|Lo que nace del miedo|Maldiciones',
      'Bleach|Un adolescente hereda el trabajo de guiar almas|Hereda guiar almas|Almas',
      'Tokyo Ghoul|Deja de ser humano y no puede comer como antes|Deja de ser humano|Hambre',
      'Hunter x Hunter|Un niño busca al padre que lo abandonó|Busca al padre que lo dejó|Búsqueda',
      'Cowboy Bebop|Perdedores con estilo cazando prófugos|Perdedores con estilo|Melancolía',
      'Chainsaw Man|Un pobre diablo fusionado con su mascota demonio|Fusionado con su mascota|Caos',
      'Spy x Family|Cada miembro esconde lo que realmente es|Cada uno esconde lo que es|Secretos',
      'Haikyuu|Un chico bajito quiere dominar un deporte de altos|Un bajito entre altos|Equipo',
      'Slam Dunk|Un delincuente se mete a un equipo por una chica|Se mete al equipo por una chica|Redención',
      'Inuyasha|Una chica cae al pasado y no puede volver|Cae al pasado y no vuelve|Portal',
      'Digimon|Niños atrapados en un mundo dentro del computador|Atrapados dentro del computador|Digital',
      'Doraemon|Un aparato del futuro le soluciona todo a un flojo|Le solucionan todo a un flojo|Futuro',
      'Shingeki no Kyojin|Gigantes devoran a los que viven tras las murallas|Devoran tras las murallas|Gigantes',
      'Your Name|Dos desconocidos despiertan en el cuerpo del otro|Despiertan en otro cuerpo|Destino',
      'El viaje de Chihiro|Una niña trabaja para recuperar a sus padres|Trabaja por recuperar a sus padres|Magia',
      'Mi vecino Totoro|Dos hermanas encuentran algo mágico en el bosque|Algo mágico en el bosque|Bosque',
      'Steins;Gate|Cambiar el pasado empeora todo lo demás|Cambiar el pasado empeora todo|Paradoja',
      'Code Geass|Un príncipe exiliado puede obligarte a obedecer|Puede obligarte a obedecer|Rebelión',
      'Berserk|Un guerrero marcado carga con una traición brutal|Carga con una traición brutal|Traición'
    ]
  },
  {
    id: 'comida',
    name: 'Comida',
    emoji: '🍕',
    words: [
      'Pizza|Se pide para compartir y se reparte en porciones|Se reparte en porciones|Compartir',
      'Hamburguesa|Comida rápida que se come con las manos|Rápida y con las manos|Rápida',
      'Sushi|Viene de Japón y se moja en salsa oscura|Japonesa y se moja en salsa|Japón',
      'Tacos|Callejero mexicano que se dobla para comer|Callejero mexicano|Callejero',
      'Empanada|La masa esconde lo bueno adentro|Lo bueno va escondido|Relleno',
      'Asado|Excusa para juntarse un domingo entero|Excusa para juntarse|Domingo',
      'Completo|El clásico chileno de la esquina|Clásico chileno de esquina|Chileno',
      'Pastel|Aparece cuando alguien cumple años|Aparece en los cumpleaños|Cumpleaños',
      'Helado|Se derrite si te demoras|Se derrite si te demoras|Frío',
      'Chocolate|El antojo dulce por excelencia|El antojo por excelencia|Antojo',
      'Ensalada|Lo que pides cuando quieres portarte bien|Cuando quieres portarte bien|Liviano',
      'Sopa|Reconforta cuando estás enfermo|Reconforta al enfermo|Caliente',
      'Arroz|Alimenta a media humanidad|Alimenta a media humanidad|Básico',
      'Papas Fritas|El acompañamiento que nadie rechaza|Nadie lo rechaza|Acompañamiento',
      'Pan|Está en la mesa de casi todas las culturas|Está en casi toda cultura|Cotidiano',
      'Queso|Mientras más añejo, más caro y más fuerte|Más añejo, más caro|Añejo',
      'Pollo Frito|Cadena de comida rápida y balde para compartir|Balde para compartir|Cadena',
      'Lasaña|Italiana, se arma por pisos y se hornea|Italiana y se arma por pisos|Pisos',
      'Ceviche|No se cocina con fuego sino con ácido|No se cocina con fuego|Ácido',
      'Sopaipilla|Se compra en la calle los días de lluvia|De la calle en días de lluvia|Lluvia',
      'Churrasco|Sándwich chileno bien cargado|Sándwich chileno cargado|Cargado',
      'Ramen|Se come con palitos y hay que sorber|Con palitos y hay que sorber|Caldo',
      'Paella|Se cocina para muchos en un solo recipiente|Para muchos en un solo recipiente|Fiesta',
      'Tortilla|Plato español que se hace con dos ingredientes|Española de dos ingredientes|España',
      'Panqueques|Desayuno dominical que se apila|Desayuno que se apila|Domingo',
      'Donut|Dulce con hoyo, favorito de los policías del cine|Dulce con hoyo|Hoyo',
      'Palomitas|Sin esto la película no es lo mismo|Sin esto la película no es igual|Cine',
      'Café|Sin esto medio mundo no arranca|Medio mundo no arranca sin esto|Despertar',
      'Mote con Huesillo|Refresco chileno de verano, se come y se bebe|Se come y se bebe a la vez|Verano',
      'Sandía|Fruta de verano, pesadísima y con pepas|De verano, pesada y con pepas|Verano'
    ]
  },
  {
    id: 'deportes',
    name: 'Deportes',
    emoji: '⚽',
    words: [
      'Fútbol|Lo ve medio planeta y no se toca con las manos|No se toca con las manos|Masivo',
      'Básquetbol|Ayuda mucho ser alto|Ayuda ser alto|Altura',
      'Tenis|Uno contra uno y el marcador se cuenta raro|Uno contra uno, marcador raro|Individual',
      'Natación|Se compite bajo techo y en traje mínimo|Bajo techo y en traje mínimo|Agua',
      'Boxeo|Dos personas se miden por asaltos|Dos se miden por asaltos|Asaltos',
      'Ciclismo|Resistencia brutal sobre dos ruedas|Resistencia sobre dos ruedas|Resistencia',
      'Atletismo|El deporte más antiguo: correr, saltar, lanzar|Correr, saltar, lanzar|Antiguo',
      'Voleibol|El suelo es el enemigo|El suelo es el enemigo|Red',
      'Golf|Elegante, lento y carísimo|Elegante, lento y carísimo|Paciencia',
      'Rugby|Contacto durísimo y sin protecciones|Contacto durísimo sin protección|Contacto',
      'Béisbol|Pasión de Estados Unidos, se batea y se corre|Pasión de Estados Unidos|Bases',
      'Surf|Depende del clima y del mar|Depende del clima y del mar|Olas',
      'Skate|Urbano, de calle y con muchos golpes|Urbano y con muchos golpes|Calle',
      'Ajedrez|No mueves el cuerpo pero terminas agotado|No mueves el cuerpo y agotas|Estrategia',
      'Karate|Disciplina oriental donde se pelea sin armas|Oriental y sin armas|Disciplina',
      'Judo|Usar la fuerza del rival en su contra|La fuerza del rival en su contra|Derribo',
      'Escalada|Solo se mira hacia arriba|Solo se mira hacia arriba|Vértigo',
      'Patinaje|Deslizarse con elegancia sobre superficie helada|Elegancia sobre lo helado|Deslizar',
      'Esquí|De invierno y hay que subir para bajar|Subir para bajar|Nieve',
      'Fórmula 1|Millonario, ruidoso y peligrosísimo|Millonario y peligrosísimo|Velocidad',
      'Maratón|Larguísimo, mucha gente termina caminando|Larguísimo y muchos caminan|Distancia',
      'Halterofilia|Levantar todo lo que se pueda de una vez|Todo el peso de una vez|Fuerza',
      'Gimnasia|Flexibilidad imposible y aterrizar clavado|Flexibilidad imposible|Flexibilidad',
      'Hockey|Se juega con un palo y en equipo|Con un palo y en equipo|Palo',
      'Waterpolo|Agotador porque no puedes pisar el fondo|No puedes pisar el fondo|Agotador',
      'Tenis de Mesa|Versión bajo techo de otro deporte, reflejos puros|Reflejos puros bajo techo|Reflejos',
      'Bádminton|Parece fácil hasta que lo juegas|Parece fácil hasta que juegas|Liviano',
      'Arquería|Puntería fina y pulso firme a distancia|Pulso firme a distancia|Puntería',
      'Esgrima|Duelo con protección y toques que dan punto|Duelo con toques que puntúan|Duelo',
      'Triatlón|Tres disciplinas seguidas sin descansar|Tres seguidas sin descanso|Tres'
    ]
  },
  {
    id: 'lugares',
    name: 'Países y Lugares',
    emoji: '🌍',
    words: [
      'París|La ciudad más romántica del mundo|La más romántica|Romance',
      'Japón|Ordenadísimo y adelantado décadas|Ordenadísimo y adelantado|Oriente',
      'Egipto|Civilización antiquísima junto a un río|Antiquísimo junto a un río|Antigüedad',
      'Brasil|El país más fiestero de Sudamérica|El más fiestero del continente|Fiesta',
      'Chile|Larguísimo, entre montaña y mar|Entre montaña y mar|Angosto',
      'Argentina|Nuestro vecino, orgulloso y futbolero|Vecino orgulloso y futbolero|Vecino',
      'México|Colorido, picante y muy tradicional|Colorido, picante y tradicional|Picante',
      'Italia|Cuna del arte y se come increíble|Cuna del arte y se come genial|Arte',
      'España|Nos dejó el idioma y la siesta|Nos dejó el idioma|Idioma',
      'China|El país con más habitantes|El de más habitantes|Multitud',
      'Nueva York|La ciudad que nunca duerme|La que nunca duerme|Rascacielos',
      'Londres|Gris, lluvioso y con monarquía|Gris y con monarquía|Monarquía',
      'Rusia|Enorme, helado y poco simpático|Enorme y helado|Frío',
      'Australia|Aislado y con la fauna más rara|Aislado y con fauna rara|Aislado',
      'India|Multitudes, colores y especias|Multitudes y especias|Especias',
      'Alemania|Puntual, industrial y cervecero|Puntual e industrial|Puntualidad',
      'Grecia|Donde nació la democracia|Donde nació la democracia|Mitología',
      'Canadá|Educadísimo y congelado|Educadísimo y congelado|Cortesía',
      'Perú|Se come de maravilla y tiene ruinas antiguas|Se come de maravilla|Ruinas',
      'Islandia|Poquísima gente y paisajes irreales|Poquísima gente, paisajes irreales|Volcanes',
      'Machu Picchu|Hay que subir muchísimo para llegar|Hay que subir muchísimo|Altura',
      'Amazonas|El pulmón verde del planeta|El pulmón del planeta|Selva',
      'Sahara|Kilómetros sin una gota de agua|Sin una gota de agua|Sequía',
      'Everest|Mucha gente ha muerto intentando llegar arriba|Muchos murieron intentándolo|Cumbre',
      'Venecia|Se hunde de a poco y no hay autos|Se hunde y no hay autos|Canales',
      'Dubái|Petróleo convertido en lujo absurdo|Lujo absurdo del petróleo|Lujo',
      'Hawái|Paraíso tropical de Estados Unidos|Paraíso tropical|Tropical',
      'Antártica|El lugar más inhóspito de la Tierra|El más inhóspito|Hielo',
      'Las Vegas|Vas a perder plata pero te vas contento|Pierdes plata y te vas contento|Apuestas',
      'Río de Janeiro|Playa, favela y una vista famosísima|Playa y favela|Carnaval'
    ]
  },
  {
    id: 'profesiones',
    name: 'Profesiones',
    emoji: '👩‍⚕️',
    words: [
      'Doctor|Estudia una eternidad y le confías tu vida|Le confías tu vida|Salud',
      'Profesor|Mal pagado y aguanta a los que no quieren estar ahí|Aguanta a quien no quiere estar|Paciencia',
      'Bombero|Corre hacia el peligro cuando todos arrancan|Corre hacia el peligro|Valor',
      'Policía|Uniformado, y la gente lo quiere u odia|Lo quieren o lo odian|Autoridad',
      'Chef|Trabaja con calor, apuro y gritos|Calor, apuro y gritos|Cocina',
      'Abogado|Cobra por hora y siempre gana alguien|Cobra por hora|Leyes',
      'Ingeniero|Todo tiene que calzar con los números|Todo calza con números|Cálculo',
      'Programador|Ocho horas sentado frente a una pantalla|Ocho horas frente a la pantalla|Pantalla',
      'Piloto|Miles de vidas dependen de que no se equivoque|Miles dependen de él|Alturas',
      'Enfermera|Turnos eternos y hace el trabajo que nadie ve|Hace el trabajo que nadie ve|Turnos',
      'Arquitecto|Imagina lo que otros van a construir|Imagina lo que otros construyen|Diseño',
      'Peluquero|Te escucha los problemas mientras trabaja|Te escucha mientras trabaja|Corte',
      'Mecánico|Termina el día con las manos negras|Termina con las manos negras|Grasa',
      'Dentista|Nadie quiere ir, todos tienen que ir|Nadie quiere ir|Muelas',
      'Veterinario|Sus pacientes no le pueden contar qué les duele|Sus pacientes no hablan|Animales',
      'Astronauta|De los trabajos más difíciles de conseguir|De los más difíciles de conseguir|Espacio',
      'Futbolista|Se retira a los treinta y cinco siendo millonario|Se retira joven y millonario|Cancha',
      'Cantante|Vive de gustar y de llenar recintos|Vive de gustar|Escenario',
      'Actor|Le pagan por ser otra persona|Le pagan por ser otro|Papel',
      'Youtuber|Trabajo que no existía hace veinte años|No existía hace veinte años|Cámara',
      'Periodista|Molesta preguntando lo que otros callan|Pregunta lo que otros callan|Preguntas',
      'Contador|En marzo no duerme|En marzo no duerme|Números',
      'Psicólogo|Le pagas por que te escuche una hora|Le pagas por escucharte|Escuchar',
      'Panadero|Cuando te levantas, él ya lleva horas|Ya lleva horas cuando despiertas|Madrugada',
      'Agricultor|Un mal año de clima lo arruina|Un mal clima lo arruina|Tierra',
      'Pescador|Se levanta de madrugada y depende de la suerte|Depende de la suerte|Paciencia',
      'Barista|Oficio nuevo para algo de toda la vida|Oficio nuevo de algo antiguo|Aroma',
      'Fotógrafo|Congela un instante para siempre|Congela un instante|Instante',
      'Científico|Se equivoca mil veces para acertar una|Se equivoca mil veces|Método',
      'Basurero|Si falta una semana, la ciudad colapsa|Si falta, la ciudad colapsa|Invisible'
    ]
  },
  {
    id: 'objetos',
    name: 'Objetos de casa',
    emoji: '🏠',
    words: [
      'Refrigerador|Lo único que jamás apagas|Lo único que nunca apagas|Frío',
      'Microondas|Rápido, cómodo y calienta desigual|Rápido y calienta desigual|Rápido',
      'Televisor|Alrededor de esto se sienta la familia|La familia se sienta alrededor|Pantalla',
      'Sofá|Donde no haces absolutamente nada|Donde no haces nada|Descanso',
      'Cama|Cuesta muchísimo abandonarla en la mañana|Cuesta abandonarla en la mañana|Sueño',
      'Espejo|Te muestra lo que no siempre quieres ver|Muestra lo que no quieres ver|Reflejo',
      'Escoba|Herramienta simple y de toda la vida|Herramienta simple de toda la vida|Limpieza',
      'Lavadora|Le entregas la ropa sucia y esperas|Le entregas lo sucio y esperas|Ropa',
      'Ducha|Ahí se te ocurren las mejores ideas|Ahí se te ocurren ideas|Agua',
      'Almohada|Sin esto no duermes bien|Sin esto no duermes bien|Blando',
      'Reloj|Nos organiza a todos y no perdona|Nos organiza y no perdona|Tiempo',
      'Cortina|Decide cuánta luz entra|Decide cuánta luz entra|Luz',
      'Lámpara|Se vuelve indispensable al atardecer|Indispensable al atardecer|Noche',
      'Ventilador|Amigo del verano, ruidoso y con aspas|Amigo del verano|Verano',
      'Estufa|Amigo del invierno, se pelean por estar cerca|Se pelean por estar cerca|Invierno',
      'Tostadora|Un solo trabajo y lo hace en un minuto|Un solo trabajo en un minuto|Desayuno',
      'Hervidor|Avisa solo cuando ya está listo|Avisa solo cuando está listo|Vapor',
      'Cuchillo|Útil y peligroso a la vez|Útil y peligroso|Filo',
      'Tenedor|Cubierto que pincha|Cubierto que pincha|Pinchar',
      'Plato|Se rompe apenas se te resbala|Se rompe si se resbala|Frágil',
      'Basurero|Se llena siempre más rápido de lo que crees|Se llena más rápido de lo que crees|Desechos',
      'Llaves|Sin esto te quedas afuera|Sin esto te quedas afuera|Abrir',
      'Control Remoto|Siempre desaparece entre los cojines|Desaparece entre los cojines|Botones',
      'Aspiradora|Ruidosa pero deja todo impecable|Ruidosa pero deja impecable|Ruido',
      'Alfombra|Esconde lo que se cae y junta polvo|Esconde lo que se cae|Suelo',
      'Silla|El mueble más repetido del mundo|El mueble más repetido|Sentarse',
      'Ventana|Tu conexión con lo que pasa afuera|Conexión con lo de afuera|Vidrio',
      'Puerta|Decide quién entra y quién no|Decide quién entra|Entrada',
      'Enchufe|Sin esto nada funciona en la casa|Sin esto nada funciona|Corriente',
      'Cargador|Nunca lo encuentras cuando queda 5%|Nunca aparece con 5%|Batería'
    ]
  },
  {
    id: 'videojuegos',
    name: 'Videojuegos',
    emoji: '🎮',
    words: [
      'Minecraft|Construyes lo que se te ocurra, sin objetivo fijo|Construyes sin objetivo fijo|Construir',
      'Fortnite|Gratis, colorido y sobrevive el último|Gratis y sobrevive el último|Supervivencia',
      'Mario Bros|El personaje más famoso de los videojuegos|El personaje más famoso|Salto',
      'Zelda|Aventura enorme, explorar y resolver templos|Explorar y resolver templos|Aventura',
      'Among Us|Alguien del grupo miente y hay que descubrirlo|Alguien del grupo miente|Sospecha',
      'Fall Guys|Torpe y gracioso, muchos compiten a la vez|Torpe, gracioso y multitudinario|Torpeza',
      'Roblox|Plataforma donde los propios niños crean los juegos|Los niños crean los juegos|Plataforma',
      'GTA|Ciudad abierta donde puedes hacer cualquier barbaridad|Puedes hacer cualquier barbaridad|Libertad',
      'Call of Duty|Bélico, sale uno nuevo cada año|Bélico y sale uno cada año|Guerra',
      'League of Legends|Competitivo por equipos, y la comunidad es tóxica|La comunidad es tóxica|Equipos',
      'Valorant|Táctico, por rondas y hay que apuntar bien|Táctico y hay que apuntar|Rondas',
      'FIFA|Simulador deportivo que sale cada temporada|Deportivo de cada temporada|Deporte',
      'The Sims|Controlas la vida cotidiana de otros|Controlas la vida de otros|Simulación',
      'Tetris|Simplísimo, antiquísimo y adictivo|Simplísimo y adictivo|Encajar',
      'Pac-Man|De los primeros y todo el mundo lo reconoce|De los primeros y todos lo reconocen|Clásico',
      'Sonic|Rival azul de otra mascota famosa|Rival azul de otra mascota|Rapidez',
      'Candy Crush|De celular, colorido y te pide plata para seguir|De celular y te pide plata|Adictivo',
      'Angry Birds|De celular, física y puntería|De celular, física y puntería|Puntería',
      'Counter-Strike|Táctico por equipos y hay que plantar algo|Táctico y hay que plantar algo|Rondas',
      'Overwatch|Equipos donde cada personaje cumple un rol|Cada personaje cumple un rol|Roles',
      'Elden Ring|Enorme, oscuro y castiga cada error|Enorme y castiga cada error|Dureza',
      'Dark Souls|Famoso por lo injusto que se siente|Famoso por lo injusto|Morir',
      'Resident Evil|Terror, munición escasa y sustos|Terror con munición escasa|Terror',
      'Silent Hill|Terror psicológico y ambiente opresivo|Terror psicológico y opresivo|Psicológico',
      'Halo|Ciencia ficción militar que definió una consola|Ciencia ficción que definió una consola|Consola',
      'God of War|Violento, mitológico y muy cinematográfico|Violento y mitológico|Furia',
      'Red Dead Redemption|Del viejo oeste, lento y melancólico|Lento y melancólico|Oeste',
      'Mario Kart|Carreras familiares donde el último tiene ventaja|El último tiene ventaja|Trampas',
      'Pokémon Go|Te obliga a salir de la casa|Te obliga a salir de casa|Caminar',
      'Clash Royale|De celular, partidas de tres minutos|Partidas de tres minutos|Cartas'
    ]
  },
  {
    id: 'series',
    name: 'Series de TV',
    emoji: '📺',
    words: [
      'Breaking Bad|Un hombre común se convierte en lo peor|Un común se vuelve lo peor|Transformación',
      'Stranger Things|Ochentera, nostálgica y con niños en bicicleta|Ochentera y nostálgica|Nostalgia',
      'Game of Thrones|Todos quieren el poder y nadie está a salvo|Nadie está a salvo|Poder',
      'The Office|Comedia sobre lo absurdo del trabajo diario|Lo absurdo del trabajo diario|Oficina',
      'Friends|Noventera, un grupo inseparable en Nueva York|Un grupo inseparable|Amistad',
      'La Casa de Papel|Española, un plan perfecto que se complica|Plan perfecto que se complica|Plan',
      'Dark|Alemana, familiar y hay que verla dos veces|Hay que verla dos veces|Confusión',
      'Black Mirror|Capítulos sueltos que te dejan incómodo|Te deja incómodo|Incomodidad',
      'The Walking Dead|Lo peor no son los muertos sino los vivos|Lo peor son los vivos|Supervivencia',
      'Los Simpsons|Lleva décadas y ya predijo de todo|Lleva décadas y predijo todo|Décadas',
      'Rick y Morty|Ciencia, humor negro y nihilismo|Humor negro y nihilismo|Dimensiones',
      'Peaky Blinders|Inglesa, familia criminal de época|Familia criminal de época|Gánsteres',
      'Narcos|Basada en hechos reales de Colombia|Basada en hechos reales|Cartel',
      'Chernobyl|Reconstruye un desastre real soviético|Un desastre real soviético|Desastre',
      'The Last of Us|Adaptada de un videojuego, padre e hija postapocalípticos|Adaptada de un videojuego|Infección',
      'Wednesday|Adolescente gótica que odia a todo el mundo|Gótica que odia a todos|Gótica',
      'Squid Game|Coreana, gente endeudada apuesta la vida|Endeudados apuestan la vida|Deudas',
      'Vikingos|Histórica, saqueos y creencias paganas|Saqueos y creencias paganas|Saqueo',
      'Sherlock|Detective moderno, brillante e insoportable|Brillante e insoportable|Deducción',
      'House|Médica, un genio que trata pésimo a todos|Genio que trata pésimo a todos|Diagnóstico',
      'Grey\'s Anatomy|Médica, eterna y muy dramática|Eterna y muy dramática|Hospital',
      'Better Call Saul|Precuela de otra serie muy famosa|Precuela de otra famosa|Precuela',
      'The Mandalorian|Del universo de una saga espacial|De una saga espacial|Galaxia',
      'Lost|Empezó genial y el final decepcionó a todos|El final decepcionó a todos|Isla',
      'Prison Break|Un plan larguísimo para sacar a alguien|Un plan larguísimo para sacar a alguien|Escape',
      'Mr. Robot|Paranoia, tecnología y salud mental|Paranoia y salud mental|Paranoia',
      'Euphoria|Adolescentes, excesos y estética muy cuidada|Excesos y estética cuidada|Excesos',
      'Bridgerton|De época, romance y chismes de salón|Romance y chismes de salón|Chismes',
      'Money Heist|La versión internacional de una española|Versión internacional de una española|Atraco',
      'Merlí|Catalana, un profesor poco convencional|Profesor poco convencional|Filosofía'
    ]
  },
  {
    id: 'musica',
    name: 'Música y Artistas',
    emoji: '🎵',
    words: [
      'Michael Jackson|El artista más famoso del siglo pasado|El más famoso del siglo pasado|Baile',
      'The Beatles|Cambiaron la música para siempre, cuatro británicos|Cambiaron la música para siempre|Cuatro',
      'Queen|Banda británica con un vocalista irrepetible|Vocalista irrepetible|Estadios',
      'Shakira|Colombiana famosa mundialmente y muy bailarina|Colombiana muy bailarina|Caderas',
      'Bad Bunny|El artista más escuchado del mundo hace poco|El más escuchado hace poco|Urbano',
      'Taylor Swift|Sus giras mueven la economía de un país|Sus giras mueven economías|Giras',
      'Beyoncé|Empezó en un grupo y se hizo enorme sola|Empezó en grupo y se hizo enorme|Diva',
      'Daddy Yankee|Popularizó un género urbano en todo el mundo|Popularizó un género urbano|Pionero',
      'Coldplay|Banda británica de estadios y luces|Británicos de estadios y luces|Pulseras',
      'Nirvana|Definió una década y terminó en tragedia|Definió una década y acabó en tragedia|Noventa',
      'Rihanna|Dejó de sacar discos y se hizo empresaria|Dejó la música y se hizo empresaria|Negocios',
      'Eminem|Blanco en un género donde no lo esperaban|Blanco donde no lo esperaban|Rimas',
      'Karol G|Colombiana urbana, enorme en los últimos años|Colombiana urbana muy reciente|Colores',
      'Maluma|Colombiano urbano, muy romántico|Colombiano urbano y romántico|Romance',
      'Elvis Presley|Ídolo de los cincuenta, murió joven|Ídolo de los cincuenta|Cincuenta',
      'Bob Marley|Jamaicano, símbolo de paz y de un género lento|Símbolo de paz|Jamaica',
      'Rock|Género rebelde, ruidoso y de guitarras|Rebelde y de guitarras|Rebeldía',
      'Reggaetón|Género urbano latino, odiado y bailado|Odiado y bailado|Perreo',
      'Cumbia|Suena en toda fiesta familiar latinoamericana|Suena en toda fiesta familiar|Fiesta',
      'Salsa|Caribeña, se baila de a dos|Caribeña y de a dos|Pareja',
      'Jazz|Elegante, complejo y muy improvisado|Complejo y muy improvisado|Improvisar',
      'Ópera|Clásica, teatral y con voces sin amplificar|Teatral y sin amplificar|Lírico',
      'Guitarra|El instrumento más aprendido del mundo|El más aprendido del mundo|Cuerdas',
      'Piano|Instrumento grande, pesado y muy completo|Grande, pesado y muy completo|Teclas',
      'Batería|Instrumento que marca el ritmo y molesta a los vecinos|Marca el ritmo y molesta al vecino|Ritmo',
      'Violín|Clásico, chiquito y dificilísimo de aprender|Chiquito y dificilísimo|Arco',
      'Karaoke|Cantar mal en público y pasarlo bien|Cantar mal en público|Vergüenza',
      'Concierto|Pagas caro, vas lejos y vale la pena|Pagas caro y vale la pena|Multitud',
      'Spotify|Reemplazó a comprar discos|Reemplazó a comprar discos|Playlists',
      'Audífonos|Te aíslan del mundo en el transporte|Te aíslan en el transporte|Aislarse'
    ]
  },
  {
    id: 'superheroes',
    name: 'Superhéroes',
    emoji: '🦸',
    words: [
      'Superman|El primero de todos, prácticamente invencible|El primero y casi invencible|Invencible',
      'Batman|Sin poderes, solo dinero y disciplina|Solo dinero y disciplina|Oscuridad',
      'Spider-Man|Joven, bromista y siempre sin plata|Joven, bromista y sin plata|Juventud',
      'Iron Man|Genio millonario, todo su poder es tecnología|Su poder es tecnología|Tecnología',
      'Hulk|Su fuerza depende de cuánto lo saques de quicio|Depende de cuánto lo saques de quicio|Ira',
      'Thor|Dios nórdico, arrogante y con un arma legendaria|Nórdico y arrogante|Trueno',
      'Capitán América|Símbolo patriótico congelado décadas|Símbolo patriótico congelado|Patriota',
      'Wonder Woman|Guerrera de una isla solo de mujeres|De una isla solo de mujeres|Amazona',
      'Flash|Su único poder es la velocidad, y le sobra|Su único poder le sobra|Velocidad',
      'Aquaman|Del que todos se burlaban hasta hace poco|Todos se burlaban de él|Océano',
      'Black Panther|Rey africano de un país tecnológico oculto|Rey de un país oculto|Realeza',
      'Deadpool|Se ríe de todo y habla contigo directamente|Se ríe de todo y te habla|Sarcasmo',
      'Wolverine|Se regenera, no envejece y es un amargado|Se regenera y es un amargado|Regeneración',
      'Doctor Strange|Cirujano que terminó estudiando lo místico|Cirujano que estudió lo místico|Místico',
      'Loki|Villano tan carismático que se volvió querido|Villano tan carismático que se volvió querido|Engaño',
      'Thanos|Cree que exterminar a la mitad es lo correcto|Cree que exterminar es correcto|Equilibrio',
      'Joker|El villano más famoso de los cómics|El villano más famoso|Caos',
      'Venom|Enemigo oscuro de un héroe arácnido|Enemigo oscuro de un arácnido|Simbiosis',
      'Ant-Man|Su poder es el tamaño, y suena ridículo|Su poder suena ridículo|Tamaño',
      'Groot|Solo dice una frase y aun así te encariñas|Solo dice una frase|Madera',
      'Rocket|Animal parlante, malhumorado y armado|Animal parlante y malhumorado|Armas',
      'Star-Lord|Lidera un grupo espacial y vive en los ochenta|Vive en los ochenta|Ochenta',
      'Robin|Siempre a la sombra de otro más famoso|Siempre a la sombra de otro|Segundo',
      'Catwoman|Ladrona ágil, ni buena ni mala|Ni buena ni mala|Ladrona',
      'Green Lantern|Su poder viene de un objeto y de la voluntad|Su poder viene de la voluntad|Voluntad',
      'Profesor X|Lidera y protege a los que nacieron distintos|Protege a los que nacieron distintos|Mente',
      'Magneto|Villano con motivos que casi entiendes|Villano con motivos que entiendes|Magnetismo',
      'Viuda Negra|Espía entrenada desde niña, sin poderes|Entrenada desde niña|Espionaje',
      'Ojo de Halcón|El más normal de un equipo de dioses|El más normal entre dioses|Precisión',
      'Shazam|Un niño con el cuerpo de un adulto poderoso|Niño con cuerpo de adulto|Rayo'
    ]
  }
];

const CATEGORIES = RAW.map((cat) => ({
  id: cat.id,
  name: cat.name,
  emoji: cat.emoji,
  words: cat.words.map((entry) => {
    const [word, facil, media, dificil] = entry.split('|');
    return {
      word: word.trim(),
      hints: {
        facil: (facil || '').trim(),
        media: (media || facil || '').trim(),
        dificil: (dificil || media || facil || '').trim()
      }
    };
  })
}));

/** Metadata liviana para el cliente (sin revelar las palabras). */
const CATEGORY_INDEX = CATEGORIES.map((c) => ({
  id: c.id,
  name: c.name,
  emoji: c.emoji,
  count: c.words.length
}));

const CATEGORY_BY_ID = new Map(CATEGORIES.map((c) => [c.id, c]));

/** Niveles de pista, del más generoso al más seco. */
const HINT_LEVELS = [
  { id: 'facil', name: 'Fácil', desc: 'Una descripción completa' },
  { id: 'media', name: 'Media', desc: 'Solo un par de señas' },
  { id: 'dificil', name: 'Difícil', desc: 'Una sola palabra' }
];
const HINT_LEVEL_IDS = HINT_LEVELS.map((l) => l.id);

module.exports = { CATEGORIES, CATEGORY_INDEX, CATEGORY_BY_ID, HINT_LEVELS, HINT_LEVEL_IDS };
